"""
HIV-1 Codon Basin Analysis - Skeptical Validation
Tests: Do high-frequency basins correspond to essential proteins?
       Do low-frequency basins reveal mutation/PTM space?
"""
import torch
import numpy as np
from collections import Counter, defaultdict
from codon_basin_counter import CodonBasinCounter, ALL_64_CODONS

# HIV-1 HXB2 Reference Genome (K03455.1) - 9719 bp
# This is the standard reference used in HIV research
HIV1_HXB2 = """
TGGAAGGGCTAATTCACTCCCAACGAAGACAAGATATCCTTGATCTGTGGATCTACCACACACAAGGCTACTTCCCTGA
TTGGCAGAACTACACACCAGGGCCAGGGATCAGATATCCACTGACCTTTGGATGGTGCTACAAGCTAGTACCAGTTGAG
CCAGAGAAGTTAGAAGAAGCCAACAAAGGAGAGAACACCAGCTTGTTACACCCTGTGAGCCTGCATGGAATGGATGACC
CTGAGAGAGAAGTGTTAGAGTGGAGGTTTGACAGCCGCCTAGCATTTCATCACATGGCCCGAGAGCTGCATCCGGAGTA
CTACAAAGACTGCTGACATCGAGCTTTCTACAAGGGACTTTCCGCTGGGGACTTTCCAGGGAGGCGTGGCCTGGGCGGG
ACTGGGGAGTGGCGAGCCCTCAGATCCTGCATATAAGCAGCTGCTTTTTGCCTGTACTGGGTCTCTCTGGTTAGACCAG
ATCTGAGCCTGGGAGCTCTCTGGCTAACTAGGGAACCCACTGCTTAAGCCTCAATAAAGCTTGCCTTGAGTGCTTCAAG
TAGTGTGTGCCCGTCTGTTGTGTGACTCTGGTAACTAGAGATCCCTCAGACCCTTTTAGTCAGTGTGGAAAATCTCTAG
CAGTGGCGCCCGAACAGGGACCTGAAAGCGAAAGGGAAACCAGAGGAGCTCTCTCGACGCAGGACTCGGCTTGCTGAAG
CGCGCACGGCAAGAGGCGAGGGGCGGCGACTGGTGAGTACGCCAAAAATTTTGACTAGCGGAGGCTAGAAGGAGAGAGA
TGGGTGCGAGAGCGTCAGTATTAAGCGGGGGAGAATTAGATCGATGGGAAAAAATTCGGTTAAGGCCAGGGGGAAAGAA
AAAATATAAATTAAAACATATAGTATGGGCAAGCAGGGAGCTAGAACGATTCGCAGTTAATCCTGGCCTGTTAGAAACA
TCAGAAGGCTGTAGACAAATACTGGGACAGCTACAACCATCCCTTCAGACAGGATCAGAAGAACTTAGATCATTATATA
ATACAGTAGCAACCCTCTATTGTGTGCATCAAAGGATAGAGATAAAAGACACCAAGGAAGCTTTAGACAAGATAGAGGA
AGAGCAAAACAAAAGTAAGAAAAAAGCACAGCAAGCAGCAGCTGACACAGGACACAGCAATCAGGTCAGCCAAAATTAC
CCTATAGTGCAGAACATCCAGGGGCAAATGGTACATCAGGCCATATCACCTAGAACTTTAAATGCATGGGTAAAAGTA
GTAGAAGAGAAGGCTTTCAGCCCAGAAGTGATACCCATGTTTTCAGCATTATCAGAAGGAGCCACCCCACAAGATTTAA
ACACCATGCTAAACACAGTGGGGGGACATCAAGCAGCCATGCAAATGTTAAAAGAGACCATCAATGAGGAAGCTGCAGA
ATGGGATAGAGTGCATCCAGTGCATGCAGGGCCTATTGCACCAGGCCAGATGAGAGAACCAAGGGGAAGTGACATAGCA
GGAACTACTAGTACCCTTCAGGAACAAATAGGATGGATGACAAATAATCCACCTATCCCAGTAGGAGAAATCTATAAAA
GATGGATAATCCTGGGATTAAATAAAATAGTAAGAATGTATAGCCCTACCAGCATTCTGGACATAAGACAAGGACCAAA
GGAACCCTTTAGAGACTATGTAGACCGGTTCTATAAAACTCTAAGAGCCGAGCAAGCTTCACAGGAGGTAAAAAATTGG
ATGACAGAAACCTTGTTGGTCCAAAATGCGAACCCAGATTGTAAGACTATTTTAAAAGCATTGGGACCAGCGGCTACAC
TAGAAGAAATGATGACAGCATGTCAGGGAGTAGGAGGACCCGGCCATAAGGCAAGAGTTTTGGCTGAAGCAATGAGCCA
AGTAACAAATTCAGCTACCATAATGATGCAGAGAGGCAATTTTAGGAACCAAAGAAAGATTGTTAAGTGTTTCAATTGT
GGCAAAGAAGGGCACACAGCCAGAAATTGCAGGGCCCCTAGGAAAAAGGGCTGTTGGAAATGTGGAAAGGAAGGACACC
AAATGAAAGATTGTACTGAGAGACAGGCTAATTTTTTAGGGAAGATCTGGCCTTCCTACAAGGGAAGGCCAGGGAATTT
TCTTCAGAGCAGACCAGAGCCAACAGCCCCACCAGAAGAGAGCTTCAGGTCTGGGGTAGAGACAACAACTCCCCCTCAG
AAGCAGGAGCCGATAGACAAGGAACTGTATCCTTTAACTTCCCTCAGGTCACTCTTTGGCAACGACCCCTCGTCACAAT
AAAGATAGGGGGGCAACTAAAGGAAGCTCTATTAGATACAGGAGCAGATGATACAGTATTAGAAGAAATGAGTTTGCCA
GGAAGATGGAAACCAAAAATGATAGGGGGAATTGGAGGTTTTATCAAAGTAAGACAGTATGATCAGATACTCATAGAAA
TCTGTGGACATAAAGCTATAGGTACAGTATTAGTAGGACCTACACCTGTCAACATAATTGGAAGAAATCTGTTGACTCA
GATTGGTTGCACTTTAAATTTTCCCATTAGCCCTATTGAGACTGTACCAGTAAAATTAAAGCCAGGAATGGATGGCCCA
AAAGTTAAACAATGGCCATTGACAGAAGAAAAAATAAAAGCATTAGTAGAAATTTGTACAGAGATGGAAAAGGAAGGGA
AAATTTCAAAAATTGGGCCTGAAAATCCATACAATACTCCAGTATTTGCCATAAAGAAAAAAGACAGTACTAAATGGAG
AAAATTAGTAGATTTCAGAGAACTTAATAAGAGAACTCAAGACTTCTGGGAAGTTCAATTAGGAATACCACATCCCGCA
GGGTTAAAAAAGAAAAAATCAGTAACAGTACTGGATGTGGGTGATGCATATTTTTCAGTTCCCTTAGATGAAGACTTCA
GGAAGTATACTGCATTTACCATACCTAGTATAAACAATGAGACACCAGGGATTAGATATCAGTACAATGTGCTTCCACA
GGGATGGAAAGGATCACCAGCAATATTCCAAAGTAGCATGACAAAAATCTTAGAGCCTTTTAGAAAACAAAATCCAGAC
ATAGTTATCTATCAATACATGGATGATTTGTATGTAGGATCTGACTTAGAAATAGGGCAGCATAGAACAAAAATAGAGG
AGCTGAGACAACATCTGTTGAGGTGGGGACTTACCACACCAGACAAAAAACATCAGAAAGAACCTCCATTCCTTTGGAT
GGGTTATGAACTCCATCCTGATAAATGGACAGTACAGCCTATAGTGCTGCCAGAAAAAGACAGCTGGACTGTCAATGAC
ATACAGAAGTTAGTGGGGAAATTGAATTGGGCAAGTCAGATTTACCCAGGGATTAAAGTAAGGCAATTATGTAAACTCC
TTAGAGGAACCAAAGCACTAACAGAAGTAATACCACTAACAGAAGAAGCAGAGCTAGAACTGGCAGAAAACAGAGAGAT
TCTAAAAGAACCAGTACATGGAGTGTATTATGACCCATCAAAAGACTTAATAGCAGAAATACAGAAGCAGGGGCAAGGC
CAATGGACATATCAAATTTATCAAGAGCCATTTAAAAATCTGAAAACAGGAAAATATGCAAGAATGAGGGGTGCCCACA
CTAATGATGTAAAACAATTAACAGAGGCAGTGCAAAAAATAACCACAGAAAGCATAGTAATATGGGGAAAGACTCCTAA
ATTTAAACTGCCCATACAAAAGGAAACATGGGAAACATGGTGGACAGAGTATTGGCAAGCCACCTGGATTCCTGAGTGG
GAGTTTGTTAATACCCCTCCCTTAGTGAAATTATGGTACCAGTTAGAGAAAGAACCCATAGTAGGAGCAGAAACCTTCT
ATGTAGATGGGGCAGCTAACAGGGAGACTAAATTAGGAAAAGCAGGATATGTTACTAATAGAGGAAGACAAAAAGTTGT
CACCCTAACTGACACAACAAATCAGAAGACTGAGTTACAAGCAATTTATCTAGCTTTGCAGGATTCGGGATTAGAAGTA
AACATAGTAACAGACTCACAATATGCATTAGGAATCATTCAAGCACAACCAGATCAAAGTGAATCAGAGTTAGTCAATC
AAATAATAGAGCAGTTAATAAAAAAGGAAAAGGTCTATCTGGCATGGGTACCAGCACACAAAGGAATTGGAGGAAATGA
ACAAGTAGATAAATTAGTCAGTGCTGGAATCAGGAAAGTACTATTTTTAGATGGAATAGATAAGGCCCAAGATGAACAT
GAGAAATATCACAGTAATTGGAGAGCAATGGCTAGTGATTTTAACCTGCCACCTGTAGTAGCAAAAGAAATAGTAGCCA
GCTGTGATAAATGTCAGCTAAAAGGAGAAGCCATGCATGGACAAGTAGACTGTAGTCCAGGAATATGGCAACTAGATTG
TACACATTTAGAAGGAAAAGTTATCCTGGTAGCAGTTCATGTAGCCAGTGGATATATAGAAGCAGAAGTTATTCCAGCA
GAGACAGGGCAGGAAACAGCATATTTTCTTTTAAAATTAGCAGGAAGATGGCCAGTAAAAACAATACATACTGACAATG
GCAGCAATTTCACCGGTGCTACGGTTAGGGCCGCCTGTTGGTGGGCGGGAATCAAGCAGGAATTTGGAATTCCCTACAA
TCCCCAAAGTCAAGGAGTAGTAGAATCTATGAATAAAGAATTAAAGAAAATTATAGGACAGGTAAGAGATCAGGCTGAA
CATCTTAAGACAGCAGTACAAATGGCAGTATTCATCCACAATTTTAAAAGAAAAGGGGGGATTGGGGGGTACAGTGCAG
GGGAAAGAATAGTAGACATAATAGCAACAGACATACAAACTAAAGAATTACAAAAACAAATTACAAAAATTCAAAATTT
TCGGGTTTATTTCAGGGACAGCAGAAATCCACTTTGGAAAGGACCAGCAAAGCTCCTCTGGAAAGGTGAAGGGGCAGTA
GTAATACAAGATAATAGTGACATAAAAGTAGTGCCAAGAAGAAAAGCAAAGATCATTAGGGATTATGGAAAACAGATGG
CAGGTGATGATTGTGTGGCAAGTAGACAGGATGAGGATTAGAACATGGAAAAGTTTAGTAAAACACCATATGTATGTTT
CAGGGAAAGCTAGGGGATGGTTTTATAGACATCACTATGAAAGCCCTCATCCAAGAATAAGTTCAGAAGTACACATCCC
ACTAGGGGATGCTAGATTGGTAATAACAACATATTGGGGTCTGCATACAGGAGAAAGAGACTGGCATTTGGGTCAGGGA
GTCTCCATAGAATGGAGGAAAAAGAGATATAGCACACAAGTAGACCCTGAACTAGCAGACCAACTAATTCATCTGTATT
ACTTTGACTGTTTTTCAGACTCTGCTATAAGAAAGGCCTTATTAGGACACATAGTTAGCCCTAGGTGTGAATATCAAGC
AGGACATAACAAGGTAGGATCTCTACAATACTTGGCACTAGCAGCATTAATAACACCAAAAAAGATAAAGCCACCTTTG
CCTAGTGTTACGAAACTGACAGAGGATAGATGGAACAAGCCCCAGAAGACCAAGGGCCACAGAGGGAGCCACACAATGA
ATGGACACTAGAGCTTTTAGAGGAGCTTAAGAATGAAGCTGTTAGACATTTTCCTAGGATTTGGCTCCATGGCTTAGGG
CAACATATCTATGAAACTTATGGGGATACTTGGGCAGGAGTGGAAGCCATAATAAGAATTCTGCAACAACTGCTGTTTA
TCCATTTTCAGAATTGGGTGTCGACATAGCAGAATAGGCGTTACTCGACAGAGGAGAGCAAGAAATGGAGCCAGTAGAT
CCTAGACTAGAGCCCTGGAAGCATCCAGGAAGTCAGCCTAAAACTGCTTGTACCAATTGCTATTGTAAAAAGTGTTGCT
TTCATTGCCAAGTTTGTTTCATAACAAAAGCCTTAGGCATCTCCTATGGCAGGAAGAAGCGGAGACAGCGACGAAGAGC
TCATCAGAACAGTCAGACTCATCAAGCTTCTCTATCAAAGCAGTAAGTAGTACATGTAATGCAACCTATACCAATAGTA
GCAATAGTGGCATTAGTAGTAGCAATAATAATAGCAATAGTTGTGTGGTCCATAGTAATCATAGAATATAGGAAAATAC
TAAGACAAAGAAAAATAGACAGGTTAATTGATAGACTAATAGAAAGAGCAGAAGACAGTGGCAATGAGAGTGAAGGAGA
AATATCAGCACTTGTGGAGATGGGGGTGGAGATGGGGCACCATGCTCCTTGGGATGTTGATGATCTGTAGTGCTACAGA
AAAATTGTGGGTCACAGTCTATTATGGGGTACCTGTGTGGAAGGAAGCAACCACCACTCTATTTTGTGCATCAGATGCT
AAAGCATATGATACAGAGGTACATAATGTTTGGGCCACACATGCCTGTGTACCCACAGACCCCAACCCACAAGAAGTAG
TATTGGTAAATGTGACAGAAAATTTTAACATGTGGAAAAATGACATGGTAGAACAGATGCATGAGGATATAATCAGTTT
ATGGGATCAAAGCCTAAAGCCATGTGTAAAATTAACCCCACTCTGTGTTAGTTTAAAGTGCACTGATTTGAAGAATGAT
ACTAATACCAATAGTAGTAGCGGGAGAATGATAATGGAGAAAGGAGAGATAAAAAACTGCTCTTTCAATATCAGCACAA
GCATAAGAGGTAAGGTGCAGAAAGAATATGCATTTTTTTATAAGCTTGATATAATACCAATAGATAATGATACTACCAG
CTATAAGTTGACAAGTTGTAACACCTCAGTCATTACACAGGCCTGTCCAAAGGTATCCTTTGAGCCAATTCCCATACAT
TATTGTGCCCCGGCTGGTTTTGCGATTCTAAAATGTAATAATAAGACGTTCAATGGAACAGGACCATGTACAAATGTCA
GCACAGTACAATGTACACATGGAATTAGGCCAGTAGTATCAACTCAACTGCTGTTAAATGGCAGTCTAGCAGAAGAAGA
GGTAGTAATTAGATCTGTCAATTTCACGGACAATGCTAAAACCATAATAGTACAGCTGAACACATCTGTAGAAATTAAT
TGTACAAGACCCAACAACAATACAAGAAAAAGAATCCGTATCCAGAGAGGACCAGGGAGAGCATTTGTTACAATAGGAA
AAATAGGAAATATGAGACAAGCACATTGTAACATTAGTAGAGCAAAATGGAATAACACTTTAAAACAGATAGCTAGCAA
ATTAAGAGAACAATTTGGAAATAATAAAACAATAATCTTTAAGCAATCCTCAGGAGGGGACCCAGAAATTGTAACGCAC
AGTTTTAATTGTGGAGGGGAATTTTTCTACTGTAATTCAACACAACTGTTTAATAGTACTTGGTTTAATAGTACTTGGA
GTACTGAAGGGTCAAATAACACTGAAGGAAGTGACACAATCACCCTCCCATGCAGAATAAAACAAATTATAAACATGTG
GCAGAAAGTAGGAAAAGCAATGTATGCCCCTCCCATCAGTGGACAAATTAGATGTTCATCAAATATTACAGGGCTGCTA
TTAACAAGAGATGGTGGTAATAGCAACAATGAGTCCGAGATCTTCAGACCTGGAGGAGGAGATATGAGGGACAATTGGA
GAAGTGAATTATATAAATATAAAGTAGTAAAAATTGAACCATTAGGAGTAGCACCCACCAAGGCAAAGAGAAGAGTGGT
GCAGAGAGAAAAAAGAGCAGTGGGAATAGGAGCTTTGTTCCTTGGGTTCTTGGGAGCAGCAGGAAGCACTATGGGCGCA
GCGTCAATGACGCTGACGGTACAGGCCAGACAATTATTGTCTGGTATAGTGCAGCAGCAGAACAATTTGCTGAGGGCTA
TTGAGGCGCAACAGCATCTGTTGCAACTCACAGTCTGGGGCATCAAGCAGCTCCAGGCAAGAATCCTGGCTGTGGAAAG
ATACCTAAAGGATCAACAGCTCCTGGGGATTTGGGGTTGCTCTGGAAAACTCATTTGCACCACTGCTGTGCCTTGGAAT
GCTAGTTGGAGTAATAAATCTCTGGAACAGATTTGGAATCACACGACCTGGATGGAGTGGGACAGAGAAATTAACAATT
ACACAAGCTTAATACACTCCTTAATTGAAGAATCGCAAAACCAGCAAGAAAAGAATGAACAAGAATTATTGGAATTAGA
TAAATGGGCAAGTTTGTGGAATTGGTTTAACATAACAAATTGGCTGTGGTATATAAAATTATTCATAATGATAGTAGGA
GGCTTGGTAGGTTTAAGAATAGTTTTTGCTGTACTTTCTATAGTGAATAGAGTTAGGCAGGGATATTCACCATTATCGT
TTCAGACCCACCTCCCAACCCCGAGGGGACCCGACAGGCCCGAAGGAATAGAAGAAGAAGGTGGAGAGAGAGACAGAGA
CAGATCCATTCGATTAGTGAACGGATCCTTGGCACTTATCTGGGACGATCTGCGGAGCCTGTGCCTCTTCAGCTACCAC
CGCTTGAGAGACTTACTCTTGATTGTAACGAGGATTGTGGAACTTCTGGGACGCAGGGGGTGGGAAGCCCTCAAATATT
GGTGGAATCTCCTACAGTATTGGAGTCAGGAACTAAAGAATAGTGCTGTTAGCTTGCTCAATGCCACAGCCATAGCAGT
AGCTGAGGGGACAGATAGGGTTATAGAAGTAGTACAAGGAGCTTGTAGAGCTATTCGCCACATACCTAGAAGAATAAGA
CAGGGCTTGGAAAGGATTTTGCTATAAGATGGGTGGCAAGTGGTCAAAAAGTAGTGTGATTGGATGGCCTACTGTAAGG
GAAAGAATGAGACGAGCTGAGCCAGCAGCAGATAGGGTGGGAGCAGCATCTCGAGACCTGGAAAAACATGGAGCAATCA
CAAGTAGCAATACAGCAGCTACCAATGCTGCTTGTGCCTGGCTAGAAGCACAAGAGGAGGAGGAGGTGGGTTTTCCAGT
CACACCTCAGGTACCTTTAAGACCAATGACTTACAAGGCAGCTGTAGATCTTAGCCACTTTTTAAAAGAAAAGGGGGG
ACTGGAAGGGCTAATTCACTCCCAAAGAAGACAAGATATCCTTGATCTGTGGATCTACCACACACAAGGCTACTTCCCT
GATTGGCAGAACTACACACCAGGGCCAGGGGTCAGATATCCACTGACCTTTGGATGGTGCTACAAGCTAGTACCAGTTG
AGCCAGATAAGATAGAAGAGGCCAATAAAGGAGAGAACACCAGCTTGTTACACCCTGTGAGCCTGCATGGGATGGATGA
CCCGGAGAGAGAAGTGTTAGAGTGGAGGTTTGACAGCCGCCTAGCATTTCATCACGTGGCCCGAGAGCTGCATCCGGAG
TACTACAAAGACTGCTGACATCGAGCTTTCTACAAGGGACTTTCCGCTGGGGACTTTCCAGGGAGGCGTGGCCTGGGCG
GGACTGGGGAGTGGCGAGCCCTCAGATCCTGCATATAAGCAGCTGCTTTTTGCCTGTACTGGGTCTCTCTGGTTAGACC
AGATCTGAGCCTGGGAGCTCTCTGGCTAACTAGGGAACCCACTGCTTAAGCCTCAATAAAGCTTGCCTTGAGTGCTTCA
"""

# Known HIV-1 protein regions (HXB2 coordinates, 0-indexed)
# These are empirically validated protein coding regions
HIV_PROTEINS = {
    'gag': (790, 2292),           # Capsid, matrix, nucleocapsid - ESSENTIAL
    'pol': (2085, 5096),          # RT, integrase, protease - ESSENTIAL
    'vif': (5041, 5619),          # Accessory
    'vpr': (5559, 5850),          # Accessory
    'tat': (5831, 6045),          # Regulatory - CRITICAL
    'rev': (5970, 6045),          # Regulatory - CRITICAL
    'vpu': (6062, 6310),          # Accessory
    'env': (6225, 8795),          # gp120, gp41 - ESSENTIAL for entry
    'nef': (8797, 9417),          # Accessory, immune evasion
}

# Proteins known to be essential vs variable
ESSENTIAL_PROTEINS = {'gag', 'pol', 'env', 'tat', 'rev'}
VARIABLE_PROTEINS = {'vif', 'vpr', 'vpu', 'nef'}


def clean_sequence(seq: str) -> str:
    """Remove whitespace and validate."""
    return ''.join(c.upper() for c in seq if c.upper() in 'ATCG')


def analyze_hiv_genome():
    """Skeptical analysis of HIV-1 codon basin distribution."""
    print("=" * 60)
    print("HIV-1 CODON BASIN ANALYSIS - SKEPTICAL VALIDATION")
    print("=" * 60)

    # Initialize counter
    counter = CodonBasinCounter()

    # Clean genome
    genome = clean_sequence(HIV1_HXB2)
    print(f"\nGenome length: {len(genome)} bp")
    print(f"Expected codons: {len(genome) // 3}")

    # Count basins for entire genome (all 3 reading frames)
    print("\n" + "-" * 40)
    print("FULL GENOME BASIN ANALYSIS (Frame 0)")
    print("-" * 40)

    full_counts = counter.encode_and_count(genome)
    stats = counter.get_basin_stats()

    print(f"Total codons: {stats['total_codons']}")
    print(f"Unique basins: {stats['unique_basins_hit']}/64 ({stats['coverage']:.1%})")
    print(f"Entropy: {stats['entropy']:.2f} bits (max: {np.log2(64):.2f})")

    # Top and bottom basins
    sorted_basins = sorted(full_counts.items(), key=lambda x: -x[1])

    print(f"\nMost frequent basins (top 10):")
    for codon, count in sorted_basins[:10]:
        pct = count / stats['total_codons'] * 100
        print(f"  {codon}: {count:4d} ({pct:.2f}%)")

    print(f"\nLeast frequent basins (bottom 10):")
    for codon, count in sorted_basins[-10:]:
        pct = count / stats['total_codons'] * 100
        print(f"  {codon}: {count:4d} ({pct:.2f}%)")

    # Analyze by protein region
    print("\n" + "-" * 40)
    print("PROTEIN-SPECIFIC BASIN ANALYSIS")
    print("-" * 40)

    protein_basins = {}
    for protein, (start, end) in HIV_PROTEINS.items():
        counter.reset_counts()
        region = genome[start:end]
        counts = counter.encode_and_count(region)
        protein_basins[protein] = {
            'counts': counts,
            'total': sum(counts.values()),
            'unique': len(counts),
            'top5': sorted(counts.items(), key=lambda x: -x[1])[:5]
        }

    # Compare essential vs variable proteins
    print("\nESSENTIAL proteins (gag, pol, env, tat, rev):")
    essential_all = Counter()
    for prot in ESSENTIAL_PROTEINS:
        if prot in protein_basins:
            info = protein_basins[prot]
            top = ', '.join(f"{c}:{n}" for c, n in info['top5'][:3])
            print(f"  {prot:4s}: {info['total']:4d} codons, {info['unique']:2d} basins | top: {top}")
            essential_all.update(info['counts'])

    print("\nVARIABLE proteins (vif, vpr, vpu, nef):")
    variable_all = Counter()
    for prot in VARIABLE_PROTEINS:
        if prot in protein_basins:
            info = protein_basins[prot]
            top = ', '.join(f"{c}:{n}" for c, n in info['top5'][:3])
            print(f"  {prot:4s}: {info['total']:4d} codons, {info['unique']:2d} basins | top: {top}")
            variable_all.update(info['counts'])

    # Key comparison: basin overlap and divergence
    print("\n" + "-" * 40)
    print("ESSENTIAL vs VARIABLE BASIN COMPARISON")
    print("-" * 40)

    essential_set = set(essential_all.keys())
    variable_set = set(variable_all.keys())
    shared = essential_set & variable_set
    essential_only = essential_set - variable_set
    variable_only = variable_set - essential_set

    print(f"Shared basins: {len(shared)}/64")
    print(f"Essential-only basins: {len(essential_only)}")
    print(f"Variable-only basins: {len(variable_only)}")

    # Hypothesis test: are rare basins in variable regions?
    print("\n" + "-" * 40)
    print("HYPOTHESIS TEST: RARE BASINS = MUTATION SPACE?")
    print("-" * 40)

    # Get bottom 20% basins from full genome
    threshold = int(len(sorted_basins) * 0.2)
    rare_basins = set(c for c, _ in sorted_basins[-threshold:])
    common_basins = set(c for c, _ in sorted_basins[:threshold])

    rare_in_essential = sum(essential_all.get(c, 0) for c in rare_basins)
    rare_in_variable = sum(variable_all.get(c, 0) for c in rare_basins)
    common_in_essential = sum(essential_all.get(c, 0) for c in common_basins)
    common_in_variable = sum(variable_all.get(c, 0) for c in common_basins)

    total_essential = sum(essential_all.values())
    total_variable = sum(variable_all.values())

    print(f"Rare basin usage:")
    print(f"  In essential proteins: {rare_in_essential}/{total_essential} ({rare_in_essential/total_essential*100:.1f}%)")
    print(f"  In variable proteins:  {rare_in_variable}/{total_variable} ({rare_in_variable/total_variable*100:.1f}%)")

    print(f"\nCommon basin usage:")
    print(f"  In essential proteins: {common_in_essential}/{total_essential} ({common_in_essential/total_essential*100:.1f}%)")
    print(f"  In variable proteins:  {common_in_variable}/{total_variable} ({common_in_variable/total_variable*100:.1f}%)")

    # Ratio analysis
    if rare_in_variable > 0 and rare_in_essential > 0:
        ratio = (rare_in_variable/total_variable) / (rare_in_essential/total_essential)
        print(f"\nRare basin enrichment in variable vs essential: {ratio:.2f}x")

    # Which codons are never used?
    unused = set(ALL_64_CODONS) - set(full_counts.keys())
    print(f"\n" + "-" * 40)
    print(f"UNUSED BASINS: {len(unused)}/64")
    print("-" * 40)
    if unused:
        print(f"  {', '.join(sorted(unused))}")
        print("  (These represent unexplored mutation space)")
    else:
        print("  All 64 basins used - full combinatorial coverage")

    # Stop codon analysis
    print(f"\n" + "-" * 40)
    print("STOP CODON BASINS (TAA, TAG, TGA)")
    print("-" * 40)
    for stop in ['TAA', 'TAG', 'TGA']:
        count = full_counts.get(stop, 0)
        print(f"  {stop}: {count} occurrences")

    return {
        'full_counts': full_counts,
        'protein_basins': protein_basins,
        'essential_all': essential_all,
        'variable_all': variable_all,
        'unused': unused
    }


if __name__ == "__main__":
    results = analyze_hiv_genome()
